CREATE TYPE "Level" AS ENUM (
  'beginner',
  'intermediate',
  'advanced'
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar NOT NULL,
  "Description" varchar NOT NULL,
  "user_id" int,
  "Level" Level,
  "Teacher" varchar NOT NULL
);

CREATE TABLE "Course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar NOT NULL,
  "Url" varchar NOT NULL,
  "Id_categoria" Int NOT NULL,
  "Id_course" Int NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "Courses" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Course_video" ADD FOREIGN KEY ("Id_categoria") REFERENCES "Categories" ("id");

ALTER TABLE "Course_video" ADD FOREIGN KEY ("Id_course") REFERENCES "Courses" ("id");

-- Users

insert into "Users" (
"name",
email,
"password",
age
) values (
'Pedro',
'pedro@hotmail.com',
'root',
'21'
);

insert into "Users" (
"name",
email,
"password",
age
) values (
'Ricaro',
'ricardo@hotmail.com',
'root',
'26'
);

-- Courses

insert into "Courses" (
"Title",
"Description",
user_id,
"Level",
"Teacher"
) values (
'Java',
'Variables',
'1',
'beginner',
'Pancho'
) , (
'Phyton',
'Funciones de Python',
'2',
'intermediate',
'Amanda'
);

-- Categories

insert into "Categories" (
"name"
) values (
'fundamentos de java'
);

insert into "Categories" (
"name"
) values (
'machine learning'
);

-- Course_video

insert into "Course_video" (
"Title" ,
"Url" ,
"Id_categoria",
"Id_course" 
) values (
'Funciones de java',
'www.youtube.com',
'1',
'2'
) , (
'machine learning python ',
'www.youtube.com',
'2',
'3'
);
